// Generated by CoffeeScript 1.8.0
(function() {
  var converter, map;

  map = require("through2-map").obj;

  converter = require('./object_converter');

  module.exports = function() {
    return map(converter);
  };

}).call(this);
